### ISSUE TITLE
Region appearing in wrong state?

### ISSUE THREAD

**Issue by Karijo35** [Bernie-2016/VolunteerDashboard#42]
In table mode for ʺCreation Statsʺ, why is ʺterrehauteʺ appearing in Illinois data.  Isn't Terre Haute in IN?

**Comment by michelledeatrick** [comment]
This is a priority. We need to move the terrehaute zip code(s) into Illinois and include this data there.

**Comment by coventry** [comment]
terrehaute [shows up for me](http://organize.berniesanders.com/volunteer-dashboard/#state=IL&startdate=&enddate=&view=tabular).  Can you give me the URL where it's not showing up?

I have updated https://github.com/coventry/cl-zip-codes to 1. Identify the primary state for the CL regions, 2. break down HI, WY, DE and DC into their counties and use the counties as regions (since those states are all effectively single regions in the original CL analysis), and 3. Assign each unassigned zip to the closest region with the same primary state.  This guarantees that every zip is assigned to the a region entirely contained in the same state.

I'll rebuild the database with these updated regions tomorrow.

**Comment by michelledeatrick** [comment]
This is great, Alex... I think some of the Wyoming counties can definitely be consolidated, though. There are so few events in WY, that having a lot of different regions isn't necessary I'm asking someone else to help identify which ones.

Also, if you could please break down the Los Angeles area further--people from that area say that using the existing Craig's list zones for Los Angeles to do this makes sense. They're here at the top of this CL page: https://losangeles.craigslist.org/

**Comment by michelledeatrick** [comment]
Here are the Los Angeles areas being requested:
Long Beach/562
Antelope Valley
San Gabriel Valley
San Fernando Valley
Westside-South Bay.

**Comment by Karijo35** [comment]
Hi -


The original issue I reported was Terre Haute was showing up in Illinois and it belongs in Indiana.


Please let me know if you need additional info.


Thanks!

Karolyn



________________________________

**Comment by coventry** [comment]
Ah, that problem should be fixed with the new assignments.  Thanks for pointing that out.

**Comment by coventry** [comment]
> Here are the Los Angeles areas being requested

@michelledeatrick, if you could get someone to make a list of a dozen or so zips near the center of each region, I can get a pretty good approximation to that by assigning the rest of the zips to the closest group.

**Comment by coventry** [comment]
@Karijo35 's original issue is fixed in ab1c78144cb4ca6605085063b7cd967e42b4713f and https://github.com/coventry/cl-zip-codes/commit/03d756bda25c98adcb7ad4073ca450e45fa296c5 .  This version of the regions is currently staged at http://gobernie.net:4999/volunteer-dashboard/
